ALTER TABLE users
    CHANGE COLUMN nome name VARCHAR(255) NOT NULL,
    CHANGE COLUMN senha password VARCHAR(255) NOT NULL,
    CHANGE COLUMN documento document VARCHAR(20) NOT NULL,
    CHANGE COLUMN tipo role ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER';
